version: '3'
services:
  web:
    build: .
    ports:
      - "5166:5000"
    networks:
      - qyt-net
  redis:
    image: "redis:alpine"
    networks:
      - qyt-net

networks:
  qyt-net:
    driver: bridge